[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[env]
term = "xterm-256color"

[window]
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"
padding = { x = 6, y = 6 }
dynamic_padding = true
# opacity = 0.875
# blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13 

[mouse]
hide_when_typing = true
