# set true color settings
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# set prefix to ctrl-a
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# change horizontal and vertical split bindings
unbind %
bind | split-window -h 
unbind '"'
bind - split-window -v

# set s to source config file
bind s source-file ~/.config/tmux/tmux.conf

# set hjkl to select panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set m to minimize/maximize panes
bind -r m resize-pane -Z

# allow mouse
set -g mouse on

# use vim movements for copy mode
set-window-option -g mode-keys vi

# start selecting text with "v"
bind-key -T copy-mode-vi 'v' send -X begin-selection 

# copy text with "y"
bind-key -T copy-mode-vi 'y' send -X copy-selection 

# don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane 

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# status bar plugin 
set -g status on 
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @tmux-dotbar-position "bottom"
# gruvbox colors
# set -g @tmux-dotbar-bg "#1d2021"
# set -g @tmux-dotbar-fg-current "#a89984"
# set -g @tmux-dotbar-fg-session "#a89984"
# set -g @tmux-dotbar-fg-prefix "#cc241d"
# everforest colors
set -g @tmux-dotbar-bg "#2d353b"
set -g @tmux-dotbar-fg-current "#7a8478"
set -g @tmux-dotbar-fg-session "#7fbbb3"
set -g @tmux-dotbar-fg-prefix "#e67e80"

# make window indexes start at one (since the indexes are not shown with this plugin)
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
